### PR TITLE
refactored the project controller

### PR DESCRIPTION
**Pull request by The-CodeINN**

### CODE REVIEW

**Comment by mide25** [comment]
Like my previous comments. You should create a service layer instead of directly fetching and manipulating data inside your controller.

**Comment by The-CodeINN** [comment]
> Like my previous comments. You should create a service layer instead of directly fetching and manipulating data inside your controller.

Like a class library??

**Comment by mide25** [comment]
> > Like my previous comments. You should create a service layer instead of directly fetching and manipulating data inside your controller.
> 
> Like a class library??

No. A Service class. Same way you have a UserRepository, you should have a UserService. UserService will do any data fetching and manipulation for your users and will simply produce the output required by your controller. 
You can read a bit about it here:
https://stackoverflow.com/a/6216013
https://pvha.hashnode.dev/mvcs-architecture

**Comment by The-CodeINN** [comment]
@mide25 @Kingriyor  I have implemented the service layer for auth and project

**Comment by benjorah** [comment]
This PR seem a bit similar to the other open one. I left some comments on that one...please check there for the ones that applies..thanks

**Pull request closed without merging**
